/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregatePasswords implements java.io.Serializable {

	private static final long serialVersionUID = 782274363;

	private java.util.UUID aggregateId;
	private byte[]         passwordHash;
	private byte[]         salt;

	public AggregatePasswords() {}

	public AggregatePasswords(
		java.util.UUID aggregateId,
		byte[] passwordHash,
		byte[] salt
	) {
		this.aggregateId = aggregateId;
		this.passwordHash = passwordHash;
		this.salt = salt;
	}

	public java.util.UUID getAggregateId() {
		return this.aggregateId;
	}

	public AggregatePasswords setAggregateId(java.util.UUID aggregateId) {
		this.aggregateId = aggregateId;
		return this;
	}

	public byte[] getPasswordHash() {
		return this.passwordHash;
	}

	public AggregatePasswords setPasswordHash(byte[] passwordHash) {
		this.passwordHash = passwordHash;
		return this;
	}

	public byte[] getSalt() {
		return this.salt;
	}

	public AggregatePasswords setSalt(byte[] salt) {
		this.salt = salt;
		return this;
	}
}
