/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DanceUserRoles implements java.io.Serializable {

	private static final long serialVersionUID = 388899179;

	private java.util.UUID    userId;
	private java.lang.Integer roleId;

	public DanceUserRoles() {}

	public DanceUserRoles(
		java.util.UUID    userId,
		java.lang.Integer roleId
	) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public java.util.UUID getUserId() {
		return this.userId;
	}

	public DanceUserRoles setUserId(java.util.UUID userId) {
		this.userId = userId;
		return this;
	}

	public java.lang.Integer getRoleId() {
		return this.roleId;
	}

	public DanceUserRoles setRoleId(java.lang.Integer roleId) {
		this.roleId = roleId;
		return this;
	}
}
