/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Domainevententry implements java.io.Serializable {

	private static final long serialVersionUID = 315385455;

	private java.lang.String aggregateidentifier;
	private java.lang.Long   sequencenumber;
	private java.lang.String type;
	private java.lang.String eventidentifier;
	private byte[]           metadata;
	private byte[]           payload;
	private java.lang.String payloadrevision;
	private java.lang.String payloadtype;
	private java.lang.String timestamp;

	public Domainevententry() {}

	public Domainevententry(
		java.lang.String aggregateidentifier,
		java.lang.Long   sequencenumber,
		java.lang.String type,
		java.lang.String eventidentifier,
		byte[]           metadata,
		byte[]           payload,
		java.lang.String payloadrevision,
		java.lang.String payloadtype,
		java.lang.String timestamp
	) {
		this.aggregateidentifier = aggregateidentifier;
		this.sequencenumber = sequencenumber;
		this.type = type;
		this.eventidentifier = eventidentifier;
		this.metadata = metadata;
		this.payload = payload;
		this.payloadrevision = payloadrevision;
		this.payloadtype = payloadtype;
		this.timestamp = timestamp;
	}

	public java.lang.String getAggregateidentifier() {
		return this.aggregateidentifier;
	}

	public Domainevententry setAggregateidentifier(java.lang.String aggregateidentifier) {
		this.aggregateidentifier = aggregateidentifier;
		return this;
	}

	public java.lang.Long getSequencenumber() {
		return this.sequencenumber;
	}

	public Domainevententry setSequencenumber(java.lang.Long sequencenumber) {
		this.sequencenumber = sequencenumber;
		return this;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public Domainevententry setType(java.lang.String type) {
		this.type = type;
		return this;
	}

	public java.lang.String getEventidentifier() {
		return this.eventidentifier;
	}

	public Domainevententry setEventidentifier(java.lang.String eventidentifier) {
		this.eventidentifier = eventidentifier;
		return this;
	}

	public byte[] getMetadata() {
		return this.metadata;
	}

	public Domainevententry setMetadata(byte[] metadata) {
		this.metadata = metadata;
		return this;
	}

	public byte[] getPayload() {
		return this.payload;
	}

	public Domainevententry setPayload(byte[] payload) {
		this.payload = payload;
		return this;
	}

	public java.lang.String getPayloadrevision() {
		return this.payloadrevision;
	}

	public Domainevententry setPayloadrevision(java.lang.String payloadrevision) {
		this.payloadrevision = payloadrevision;
		return this;
	}

	public java.lang.String getPayloadtype() {
		return this.payloadtype;
	}

	public Domainevententry setPayloadtype(java.lang.String payloadtype) {
		this.payloadtype = payloadtype;
		return this;
	}

	public java.lang.String getTimestamp() {
		return this.timestamp;
	}

	public Domainevententry setTimestamp(java.lang.String timestamp) {
		this.timestamp = timestamp;
		return this;
	}
}
