/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregatePasswordsDao extends org.jooq.impl.DAOImpl<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord, com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords, java.util.UUID> {

	/**
	 * Create a new AggregatePasswordsDao without any configuration
	 */
	public AggregatePasswordsDao() {
		super(com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS, com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords.class);
	}

	/**
	 * Create a new AggregatePasswordsDao with an attached configuration
	 */
	public AggregatePasswordsDao(org.jooq.Configuration configuration) {
		super(com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS, com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.util.UUID getId(com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords object) {
		return object.getAggregateId();
	}

	/**
	 * Fetch records that have <code>aggregate_id IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords> fetchByAggregateId(java.util.UUID... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS.AGGREGATE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>aggregate_id = value</code>
	 */
	public com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords fetchOneByAggregateId(java.util.UUID value) {
		return fetchOne(com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS.AGGREGATE_ID, value);
	}

	/**
	 * Fetch records that have <code>password_hash IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords> fetchByPasswordHash(byte[]... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS.PASSWORD_HASH, values);
	}

	/**
	 * Fetch records that have <code>salt IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.AggregatePasswords> fetchBySalt(byte[]... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS.SALT, values);
	}
}
