/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DanceUserRolesDao extends org.jooq.impl.DAOImpl<com.tartner.dancehours.querymodel.database.tables.records.DanceUserRolesRecord, com.tartner.dancehours.querymodel.database.tables.pojos.DanceUserRoles, org.jooq.Record2<java.util.UUID, java.lang.Integer>> {

	/**
	 * Create a new DanceUserRolesDao without any configuration
	 */
	public DanceUserRolesDao() {
		super(com.tartner.dancehours.querymodel.database.tables.DanceUserRoles.DANCE_USER_ROLES, com.tartner.dancehours.querymodel.database.tables.pojos.DanceUserRoles.class);
	}

	/**
	 * Create a new DanceUserRolesDao with an attached configuration
	 */
	public DanceUserRolesDao(org.jooq.Configuration configuration) {
		super(com.tartner.dancehours.querymodel.database.tables.DanceUserRoles.DANCE_USER_ROLES, com.tartner.dancehours.querymodel.database.tables.pojos.DanceUserRoles.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.util.UUID, java.lang.Integer> getId(com.tartner.dancehours.querymodel.database.tables.pojos.DanceUserRoles object) {
		return compositeKeyRecord(object.getUserId(), object.getRoleId());
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUserRoles> fetchByUserId(java.util.UUID... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUserRoles.DANCE_USER_ROLES.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>role_id IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUserRoles> fetchByRoleId(java.lang.Integer... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUserRoles.DANCE_USER_ROLES.ROLE_ID, values);
	}
}
