/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DanceUserDao extends org.jooq.impl.DAOImpl<com.tartner.dancehours.querymodel.database.tables.records.DanceUserRecord, com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser, java.util.UUID> {

	/**
	 * Create a new DanceUserDao without any configuration
	 */
	public DanceUserDao() {
		super(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER, com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser.class);
	}

	/**
	 * Create a new DanceUserDao with an attached configuration
	 */
	public DanceUserDao(org.jooq.Configuration configuration) {
		super(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER, com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.util.UUID getId(com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser object) {
		return object.getUserId();
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser> fetchByUserId(java.util.UUID... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser fetchOneByUserId(java.util.UUID value) {
		return fetchOne(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser> fetchByEmail(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser> fetchByFirstName(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser> fetchByLastName(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.LAST_NAME, values);
	}

	/**
	 * Fetch records that have <code>is_active IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser> fetchByIsActive(java.lang.Boolean... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.IS_ACTIVE, values);
	}

	/**
	 * Fetch records that have <code>user_type IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.DanceUser> fetchByUserType(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.USER_TYPE, values);
	}
}
