/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainevententryDao extends org.jooq.impl.DAOImpl<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry, org.jooq.Record3<java.lang.String, java.lang.Long, java.lang.String>> {

	/**
	 * Create a new DomainevententryDao without any configuration
	 */
	public DomainevententryDao() {
		super(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY, com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry.class);
	}

	/**
	 * Create a new DomainevententryDao with an attached configuration
	 */
	public DomainevententryDao(org.jooq.Configuration configuration) {
		super(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY, com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record3<java.lang.String, java.lang.Long, java.lang.String> getId(com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry object) {
		return compositeKeyRecord(object.getAggregateidentifier(), object.getSequencenumber(), object.getType());
	}

	/**
	 * Fetch records that have <code>aggregateidentifier IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByAggregateidentifier(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.AGGREGATEIDENTIFIER, values);
	}

	/**
	 * Fetch records that have <code>sequencenumber IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchBySequencenumber(java.lang.Long... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.SEQUENCENUMBER, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByType(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.TYPE, values);
	}

	/**
	 * Fetch records that have <code>eventidentifier IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByEventidentifier(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.EVENTIDENTIFIER, values);
	}

	/**
	 * Fetch records that have <code>metadata IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByMetadata(byte[]... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.METADATA, values);
	}

	/**
	 * Fetch records that have <code>payload IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByPayload(byte[]... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.PAYLOAD, values);
	}

	/**
	 * Fetch records that have <code>payloadrevision IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByPayloadrevision(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.PAYLOADREVISION, values);
	}

	/**
	 * Fetch records that have <code>payloadtype IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByPayloadtype(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.PAYLOADTYPE, values);
	}

	/**
	 * Fetch records that have <code>timestamp IN (values)</code>
	 */
	public java.util.List<com.tartner.dancehours.querymodel.database.tables.pojos.Domainevententry> fetchByTimestamp(java.lang.String... values) {
		return fetch(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.TIMESTAMP, values);
	}
}
