/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DanceUser extends org.jooq.impl.TableImpl<com.tartner.dancehours.database.tables.records.DanceUserRecord> {

	private static final long serialVersionUID = -1821348643;

	/**
	 * The reference instance of <code>public.dance_user</code>
	 */
	public static final com.tartner.dancehours.database.tables.DanceUser DANCE_USER = new com.tartner.dancehours.database.tables.DanceUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.tartner.dancehours.database.tables.records.DanceUserRecord> getRecordType() {
		return com.tartner.dancehours.database.tables.records.DanceUserRecord.class;
	}

	/**
	 * The column <code>public.dance_user.user_id</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.util.UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.dance_user.email</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(254).nullable(false), this, "");

	/**
	 * The column <code>public.dance_user.first_name</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.dance_user.last_name</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.dance_user.is_active</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.lang.Boolean> IS_ACTIVE = createField("is_active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>public.dance_user.password_hash</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.lang.Long> PASSWORD_HASH = createField("password_hash", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.dance_user.user_type</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.database.tables.records.DanceUserRecord, java.lang.String> USER_TYPE = createField("user_type", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>public.dance_user</code> table reference
	 */
	public DanceUser() {
		this("dance_user", null);
	}

	/**
	 * Create an aliased <code>public.dance_user</code> table reference
	 */
	public DanceUser(java.lang.String alias) {
		this(alias, com.tartner.dancehours.database.tables.DanceUser.DANCE_USER);
	}

	private DanceUser(java.lang.String alias, org.jooq.Table<com.tartner.dancehours.database.tables.records.DanceUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private DanceUser(java.lang.String alias, org.jooq.Table<com.tartner.dancehours.database.tables.records.DanceUserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.tartner.dancehours.database.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.tartner.dancehours.database.tables.records.DanceUserRecord> getPrimaryKey() {
		return com.tartner.dancehours.database.Keys.DANCE_USER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.tartner.dancehours.database.tables.records.DanceUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.tartner.dancehours.database.tables.records.DanceUserRecord>>asList(com.tartner.dancehours.database.Keys.DANCE_USER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.tartner.dancehours.database.tables.DanceUser as(java.lang.String alias) {
		return new com.tartner.dancehours.database.tables.DanceUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.tartner.dancehours.database.tables.DanceUser rename(java.lang.String name) {
		return new com.tartner.dancehours.database.tables.DanceUser(name, null);
	}
}
