/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DanceUserRecord extends org.jooq.impl.UpdatableRecordImpl<com.tartner.dancehours.querymodel.database.tables.records.DanceUserRecord> implements org.jooq.Record6<java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String> {

	private static final long serialVersionUID = 382591963;

	/**
	 * Setter for <code>public.dance_user.user_id</code>.
	 */
	public DanceUserRecord setUserId(java.util.UUID value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.dance_user.user_id</code>.
	 */
	public java.util.UUID getUserId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.dance_user.email</code>.
	 */
	public DanceUserRecord setEmail(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.dance_user.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.dance_user.first_name</code>.
	 */
	public DanceUserRecord setFirstName(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.dance_user.first_name</code>.
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.dance_user.last_name</code>.
	 */
	public DanceUserRecord setLastName(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.dance_user.last_name</code>.
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.dance_user.is_active</code>.
	 */
	public DanceUserRecord setIsActive(java.lang.Boolean value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.dance_user.is_active</code>.
	 */
	public java.lang.Boolean getIsActive() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.dance_user.user_type</code>.
	 */
	public DanceUserRecord setUserType(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.dance_user.user_type</code>.
	 */
	public java.lang.String getUserType() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER.USER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getUserType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord value1(java.util.UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord value2(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord value3(java.lang.String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord value4(java.lang.String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord value5(java.lang.Boolean value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord value6(java.lang.String value) {
		setUserType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DanceUserRecord values(java.util.UUID value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Boolean value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DanceUserRecord
	 */
	public DanceUserRecord() {
		super(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER);
	}

	/**
	 * Create a detached, initialised DanceUserRecord
	 */
	public DanceUserRecord(java.util.UUID userId, java.lang.String email, java.lang.String firstName, java.lang.String lastName, java.lang.Boolean isActive, java.lang.String userType) {
		super(com.tartner.dancehours.querymodel.database.tables.DanceUser.DANCE_USER);

		setValue(0, userId);
		setValue(1, email);
		setValue(2, firstName);
		setValue(3, lastName);
		setValue(4, isActive);
		setValue(5, userType);
	}
}
