/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainevententryRecord extends org.jooq.impl.UpdatableRecordImpl<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord> implements org.jooq.Record9<java.lang.String, java.lang.Long, java.lang.String, java.lang.String, byte[], byte[], java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1248528809;

	/**
	 * Setter for <code>public.domainevententry.aggregateidentifier</code>.
	 */
	public DomainevententryRecord setAggregateidentifier(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.aggregateidentifier</code>.
	 */
	public java.lang.String getAggregateidentifier() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.domainevententry.sequencenumber</code>.
	 */
	public DomainevententryRecord setSequencenumber(java.lang.Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.sequencenumber</code>.
	 */
	public java.lang.Long getSequencenumber() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.domainevententry.type</code>.
	 */
	public DomainevententryRecord setType(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.domainevententry.eventidentifier</code>.
	 */
	public DomainevententryRecord setEventidentifier(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.eventidentifier</code>.
	 */
	public java.lang.String getEventidentifier() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.domainevententry.metadata</code>.
	 */
	public DomainevententryRecord setMetadata(byte[] value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.metadata</code>.
	 */
	public byte[] getMetadata() {
		return (byte[]) getValue(4);
	}

	/**
	 * Setter for <code>public.domainevententry.payload</code>.
	 */
	public DomainevententryRecord setPayload(byte[] value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.payload</code>.
	 */
	public byte[] getPayload() {
		return (byte[]) getValue(5);
	}

	/**
	 * Setter for <code>public.domainevententry.payloadrevision</code>.
	 */
	public DomainevententryRecord setPayloadrevision(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.payloadrevision</code>.
	 */
	public java.lang.String getPayloadrevision() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.domainevententry.payloadtype</code>.
	 */
	public DomainevententryRecord setPayloadtype(java.lang.String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.payloadtype</code>.
	 */
	public java.lang.String getPayloadtype() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.domainevententry.timestamp</code>.
	 */
	public DomainevententryRecord setTimestamp(java.lang.String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>public.domainevententry.timestamp</code>.
	 */
	public java.lang.String getTimestamp() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.String, java.lang.Long, java.lang.String> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.Long, java.lang.String, java.lang.String, byte[], byte[], java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.Long, java.lang.String, java.lang.String, byte[], byte[], java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.AGGREGATEIDENTIFIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.SEQUENCENUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.EVENTIDENTIFIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field5() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.METADATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field6() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.PAYLOAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.PAYLOADREVISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.PAYLOADTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getAggregateidentifier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getSequencenumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEventidentifier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value5() {
		return getMetadata();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value6() {
		return getPayload();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getPayloadrevision();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getPayloadtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value1(java.lang.String value) {
		setAggregateidentifier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value2(java.lang.Long value) {
		setSequencenumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value3(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value4(java.lang.String value) {
		setEventidentifier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value5(byte[] value) {
		setMetadata(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value6(byte[] value) {
		setPayload(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value7(java.lang.String value) {
		setPayloadrevision(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value8(java.lang.String value) {
		setPayloadtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord value9(java.lang.String value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DomainevententryRecord values(java.lang.String value1, java.lang.Long value2, java.lang.String value3, java.lang.String value4, byte[] value5, byte[] value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DomainevententryRecord
	 */
	public DomainevententryRecord() {
		super(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY);
	}

	/**
	 * Create a detached, initialised DomainevententryRecord
	 */
	public DomainevententryRecord(java.lang.String aggregateidentifier, java.lang.Long sequencenumber, java.lang.String type, java.lang.String eventidentifier, byte[] metadata, byte[] payload, java.lang.String payloadrevision, java.lang.String payloadtype, java.lang.String timestamp) {
		super(com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY);

		setValue(0, aggregateidentifier);
		setValue(1, sequencenumber);
		setValue(2, type);
		setValue(3, eventidentifier);
		setValue(4, metadata);
		setValue(5, payload);
		setValue(6, payloadrevision);
		setValue(7, payloadtype);
		setValue(8, timestamp);
	}
}
