/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.database;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.dance_user
	 */
	public static final com.tartner.dancehours.database.tables.DanceUser DANCE_USER = com.tartner.dancehours.database.tables.DanceUser.DANCE_USER;

	/**
	 * The table public.dance_user_roles
	 */
	public static final com.tartner.dancehours.database.tables.DanceUserRoles DANCE_USER_ROLES = com.tartner.dancehours.database.tables.DanceUserRoles.DANCE_USER_ROLES;
}
