/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregatePasswords extends org.jooq.impl.TableImpl<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord> {

	private static final long serialVersionUID = 1467338560;

	/**
	 * The reference instance of <code>public.aggregate_passwords</code>
	 */
	public static final com.tartner.dancehours.querymodel.database.tables.AggregatePasswords AGGREGATE_PASSWORDS = new com.tartner.dancehours.querymodel.database.tables.AggregatePasswords();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord> getRecordType() {
		return com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord.class;
	}

	/**
	 * The column <code>public.aggregate_passwords.aggregate_id</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord, java.util.UUID> AGGREGATE_ID = createField("aggregate_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.aggregate_passwords.password_hash</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord, byte[]> PASSWORD_HASH = createField("password_hash", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * The column <code>public.aggregate_passwords.salt</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord, byte[]> SALT = createField("salt", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * Create a <code>public.aggregate_passwords</code> table reference
	 */
	public AggregatePasswords() {
		this("aggregate_passwords", null);
	}

	/**
	 * Create an aliased <code>public.aggregate_passwords</code> table reference
	 */
	public AggregatePasswords(java.lang.String alias) {
		this(alias, com.tartner.dancehours.querymodel.database.tables.AggregatePasswords.AGGREGATE_PASSWORDS);
	}

	private AggregatePasswords(java.lang.String alias, org.jooq.Table<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AggregatePasswords(java.lang.String alias, org.jooq.Table<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.tartner.dancehours.querymodel.database.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord> getPrimaryKey() {
		return com.tartner.dancehours.querymodel.database.Keys.AGGREGATE_PASSWORDS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.tartner.dancehours.querymodel.database.tables.records.AggregatePasswordsRecord>>asList(com.tartner.dancehours.querymodel.database.Keys.AGGREGATE_PASSWORDS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.tartner.dancehours.querymodel.database.tables.AggregatePasswords as(java.lang.String alias) {
		return new com.tartner.dancehours.querymodel.database.tables.AggregatePasswords(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.tartner.dancehours.querymodel.database.tables.AggregatePasswords rename(java.lang.String name) {
		return new com.tartner.dancehours.querymodel.database.tables.AggregatePasswords(name, null);
	}
}
