/**
 * This class is generated by jOOQ
 */
package com.tartner.dancehours.querymodel.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Domainevententry extends org.jooq.impl.TableImpl<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord> {

	private static final long serialVersionUID = 862613610;

	/**
	 * The reference instance of <code>public.domainevententry</code>
	 */
	public static final com.tartner.dancehours.querymodel.database.tables.Domainevententry DOMAINEVENTENTRY = new com.tartner.dancehours.querymodel.database.tables.Domainevententry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord> getRecordType() {
		return com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord.class;
	}

	/**
	 * The column <code>public.domainevententry.aggregateidentifier</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.String> AGGREGATEIDENTIFIER = createField("aggregateidentifier", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.domainevententry.sequencenumber</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.Long> SEQUENCENUMBER = createField("sequencenumber", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.domainevententry.type</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.domainevententry.eventidentifier</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.String> EVENTIDENTIFIER = createField("eventidentifier", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.domainevententry.metadata</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, byte[]> METADATA = createField("metadata", org.jooq.impl.SQLDataType.BLOB, this, "");

	/**
	 * The column <code>public.domainevententry.payload</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, byte[]> PAYLOAD = createField("payload", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * The column <code>public.domainevententry.payloadrevision</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.String> PAYLOADREVISION = createField("payloadrevision", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.domainevententry.payloadtype</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.String> PAYLOADTYPE = createField("payloadtype", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.domainevententry.timestamp</code>.
	 */
	public final org.jooq.TableField<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord, java.lang.String> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>public.domainevententry</code> table reference
	 */
	public Domainevententry() {
		this("domainevententry", null);
	}

	/**
	 * Create an aliased <code>public.domainevententry</code> table reference
	 */
	public Domainevententry(java.lang.String alias) {
		this(alias, com.tartner.dancehours.querymodel.database.tables.Domainevententry.DOMAINEVENTENTRY);
	}

	private Domainevententry(java.lang.String alias, org.jooq.Table<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Domainevententry(java.lang.String alias, org.jooq.Table<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.tartner.dancehours.querymodel.database.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord> getPrimaryKey() {
		return com.tartner.dancehours.querymodel.database.Keys.DOMAINEVENTENTRY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.tartner.dancehours.querymodel.database.tables.records.DomainevententryRecord>>asList(com.tartner.dancehours.querymodel.database.Keys.DOMAINEVENTENTRY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.tartner.dancehours.querymodel.database.tables.Domainevententry as(java.lang.String alias) {
		return new com.tartner.dancehours.querymodel.database.tables.Domainevententry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.tartner.dancehours.querymodel.database.tables.Domainevententry rename(java.lang.String name) {
		return new com.tartner.dancehours.querymodel.database.tables.Domainevententry(name, null);
	}
}
